spring:
  data:
    mongodb:
      host: mongodb
      database: coopvote
  kafka:
    producer:
      bootstrap-servers: kafka:9093
    consumer:
      bootstrap-servers: kafka:9092
      group-id: voting-result-consumer-group

voting:
  result:
    kafka:
      topic: voting-result

default:
  expiration:
    minutes: 1

external:
  service:
    cpf:
      url: https://user-info.herokuapp.com/users/